package com.zfz.xiaomi.dao;

import com.zfz.xiaomi.entry.GoodsOrder;
import com.zfz.xiaomi.entry.GoodsOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    long countByExample(GoodsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    int deleteByExample(GoodsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    int insert(GoodsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    int insertSelective(GoodsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    List<GoodsOrder> selectByExample(GoodsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    GoodsOrder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    int updateByExampleSelective(@Param("record") GoodsOrder record, @Param("example") GoodsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    int updateByExample(@Param("record") GoodsOrder record, @Param("example") GoodsOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    int updateByPrimaryKeySelective(GoodsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    int updateByPrimaryKey(GoodsOrder record);
}