package com.zfz.xiaomi.dao;

import com.zfz.xiaomi.entry.GoodsImages;
import com.zfz.xiaomi.entry.GoodsImagesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsImagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Sun Feb 23 17:50:08 CST 2020
     */
    long countByExample(GoodsImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Sun Feb 23 17:50:08 CST 2020
     */
    int deleteByExample(GoodsImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Sun Feb 23 17:50:08 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Sun Feb 23 17:50:08 CST 2020
     */
    int insert(GoodsImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Sun Feb 23 17:50:08 CST 2020
     */
    int insertSelective(GoodsImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Sun Feb 23 17:50:08 CST 2020
     */
    List<GoodsImages> selectByExample(GoodsImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Sun Feb 23 17:50:08 CST 2020
     */
    GoodsImages selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Sun Feb 23 17:50:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") GoodsImages record, @Param("example") GoodsImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Sun Feb 23 17:50:08 CST 2020
     */
    int updateByExample(@Param("record") GoodsImages record, @Param("example") GoodsImagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Sun Feb 23 17:50:08 CST 2020
     */
    int updateByPrimaryKeySelective(GoodsImages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_images
     *
     * @mbg.generated Sun Feb 23 17:50:08 CST 2020
     */
    int updateByPrimaryKey(GoodsImages record);
}