package com.zfz.xiaomi.entry;

public class GoodsShippingAddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_shipping_address.id
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_shipping_address.name
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_shipping_address.phone
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_shipping_address.email
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_shipping_address.province
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_shipping_address.city
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_shipping_address.country
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_shipping_address.street
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    private String street;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_shipping_address.consumer_id
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    private Integer consumerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_shipping_address.remark
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_shipping_address.id
     *
     * @return the value of goods_shipping_address.id
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_shipping_address.id
     *
     * @param id the value for goods_shipping_address.id
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_shipping_address.name
     *
     * @return the value of goods_shipping_address.name
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_shipping_address.name
     *
     * @param name the value for goods_shipping_address.name
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_shipping_address.phone
     *
     * @return the value of goods_shipping_address.phone
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_shipping_address.phone
     *
     * @param phone the value for goods_shipping_address.phone
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_shipping_address.email
     *
     * @return the value of goods_shipping_address.email
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_shipping_address.email
     *
     * @param email the value for goods_shipping_address.email
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_shipping_address.province
     *
     * @return the value of goods_shipping_address.province
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_shipping_address.province
     *
     * @param province the value for goods_shipping_address.province
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_shipping_address.city
     *
     * @return the value of goods_shipping_address.city
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_shipping_address.city
     *
     * @param city the value for goods_shipping_address.city
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_shipping_address.country
     *
     * @return the value of goods_shipping_address.country
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_shipping_address.country
     *
     * @param country the value for goods_shipping_address.country
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_shipping_address.street
     *
     * @return the value of goods_shipping_address.street
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_shipping_address.street
     *
     * @param street the value for goods_shipping_address.street
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_shipping_address.consumer_id
     *
     * @return the value of goods_shipping_address.consumer_id
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    public Integer getConsumerId() {
        return consumerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_shipping_address.consumer_id
     *
     * @param consumerId the value for goods_shipping_address.consumer_id
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    public void setConsumerId(Integer consumerId) {
        this.consumerId = consumerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_shipping_address.remark
     *
     * @return the value of goods_shipping_address.remark
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_shipping_address.remark
     *
     * @param remark the value for goods_shipping_address.remark
     *
     * @mbg.generated Sun Feb 23 17:50:09 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}